version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  linux:
    docker:
      - image: alpine
    steps:
      - checkout
      - run: ls

  windows64:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run:
          name: build
          command: .\installer.ps1
      - run: echo $Env:Path
      - run:
          name: test
          command: nvim --version

workflows:
  version: 2
  test:
    jobs:
      - windows64
      - linux
