version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  linux:
    docker:
      - image: alpine
    steps:
      - checkout
      - run: apk add curl
      - run:
          name: build
          command: sh installer.sh
      - run: ls /usr/bin
      - run: which ls
      - run: echo $PATH
      - run:
          name: test
          command: nvim --version

  windows:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run: ls

workflows:
  version: 2
  test:
    jobs:
      - windows
      - linux
