version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  linux:
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run: apt update && apt install -y curl
      - run:
          name: build
          command: sh installer.sh
      - run: 
          name: test
          command: nvim --version

  windows64:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run:
          name: build
          command: .\installer.ps1
      - run:
          name: test
          command: nvim --version

workflows:
  version: 2
  test:
    jobs:
      - windows64
      - linux
