# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  linux-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install dependences
        run: sudo apt-get update && sudo apt-get install curl git unzip

      - name: install apps
        run: |
            wget https://github.com/neovim/neovim/releases/download/v0.7.2/nvim-linux64.deb
            sudo apt-get install ./nvim-linux64.deb

      - name: build
        run: PROFILE=/home/upnt/.config/powershell/Microsoft.PowerShell_profile.ps1 ./bin/installer.sh 1 2 3 4 5 6
        
      - name: test
        run: nvim --version
